### ISSUE TITLE
[QUESTION] New World *.*db files.

### ISSUE THREAD

**Issue by Aryathel** [Kattoor/nw-datasheet-reader#1]
Hello! Sorry to bother, but I am looking for a way of accessing item listings on my own. Your datasheet reader has worked brilliantly for me, but now I am trying to find display names for items to display on the front end of the crafting calculator I am making. I am attempting to find the display information for an entry like:
```
{
        "ItemID": "2hStaffFire_BaricsSunstaffT4",
        "Name": "@2hStaffFire_BaricsSunstaffT4_MasterName",
        "ItemType": "Weapon",
        "ItemTypeDisplayName": "@ui_itemtypedescription_firestaff",
        "Description": "@2hStaffFire_BaricsSunstaffT4_Description"
}
```
My assumption is that this information is stored in the `*.*db` files in the `sharedassets/genericassets` directory, but I do not know how to go about attempting to access that. I was wondering if you had any pointers or direction you could give me for this? Any help or information you could give would be greatly appreciated, and thanks again for your awesome work on the datasheet reader!

**Comment by Kattoor** [comment]
Hey! You're trying to find the in-game names for these records, right?
You can find those in the XML files of the game, looking for the 'Name' property of the record you posted.
This is what I get for 2hFireStaff_MarauderRank1_MasterName: `<string key="2hFireStaff_MarauderRank1_MasterName">Marauder Soldier Fire Staff</string>`

To extract the XML files, make the following changes to the project:
1. nw-datasheet-reader.mjs
1.1. delete line 32
1.2. line 28: replace `/out/` by `/out_xml/`
2. datasheet-extractor.mjs: line 54: change `.datasheet$` to `.xml$`

**Comment by Aryathel** [comment]
Thanks for the help! This seems exactly like what I needed, but when I make those changes and try to access the xml files using an xml reader (in Python), it is unreadable. Is there any other steps I need to take to convert the encoded format into plaintext? I've tried decoding it in LE, UTF-8, and ANSI formats, to no avail.

**Comment by mdreier** [comment]
Some files are unreadable (contain only nulls), but most are good for me. Since you're looking for the UI names, the files in `out_xml\localization\en-us` were readable for me.

**Comment by Aryathel** [comment]
Ah, yup! There they are. Thank you for holding my hand through that! This should be everything I need, thanks again.
