### ISSUE TITLE
Running the program does nothing

### ISSUE THREAD

**Issue by Ludeo** [Kattoor/nw-datasheet-reader#2]
Hey, I downloaded the datasheet reader and executed "npm install", everything is up to date. I also made sure that I have the latest version of python and node but when I run the program it just says "Extracting datasheets.." and it's done but the out folder is empty.
I tried the following commands:

node nw-datasheet-reader.mjs csv "C:\Program Files (x86)\Steam\steamapps\common\New World\assets"
node nw-datasheet-reader.mjs csv "C:\Program Files (x86)\Steam\steamapps\common\New World\assets\"
node nw-datasheet-reader.mjs csv "C:\Program Files (x86)\Steam\steamapps\common\New World"
node nw-datasheet-reader.mjs csv "C:\Program Files (x86)\Steam\steamapps\common\New World\"

Also tried the same commands with backslashes instead of slashes but every time the out folder remains empty

**Comment by HappyCappybara** [comment]
This is an issue with Globby and getting the filepath to the datasheets.

`const pakFilePaths = await globby(assetsPath + '/**/*.pak');`

Isn't returning anything when you specify an absolute filepath to the game. As a fix I just put nw-datasheet-reader.mjs in a subdirectory of the NW install folder and specified the datasheet path as relative:

node nw-datasheet-reader.mjs json "..\\"

edit:
you'll also need to change datasheet-converter.mjs:

`const filePaths = await globby('**/*.datasheet');`

**Comment by Ludeo** [comment]
That works perfectly, thank you a lot ^^
